on: [push, pull_request]
name: build
jobs:
  build:
    name: Example
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d_%H-%M-%S')"
      - name: Test with environment variables
        run: echo $TAG_NAME - $RELEASE_NAME
        env:
          TAG_NAME: nightly-tag-${{ steps.date.outputs.date }}
          RELEASE_NAME: nightly-release-${{ steps.date.outputs.date }}
      - name: Test with input
        uses: actions/hello-world-docker-action@master
        with:
          who-to-greet: Mona-the-Octocat-${{ steps.date.outputs.date }}
      - name: dsa          
        uses: mad9000/actions-find-and-replace-string@2
        with:
          source: ${{ steps.date.outputs.date }} # this translates to ref/heads/main on the main branch, but can be any arbitrary string 
          find: '-'        # we want to remove ref/heads/ from source 
          replace: ''               # and replace it with a blank string (ie. removing it)
