name: framework-setup
on: 
  push:
    branches:
      - 'cdumitras84-patch-1'
jobs:
  test_build:
    runs-on: ubuntu-latest
    container:
      image: node:14.4
      options: --network-alias testHost
    env:
      NODE_ENV: test
      SELENIUM_HUB_HOST: hub
      TEST_HOST: testHost
    services:
      hub:
        image: selenium/hub:3.141.59-gold
      firefox:
        image: selenium/node-firefox:3.141.59-gold
      chrome:
        image: selenium/node-chrome:4.0.0-beta-3-prerelease-20210422
        env:
          HUB_HOST: hub
          HUB_PORT: 4444
    steps:
      - name: Checkout
        uses: actions/checkout@v1.2.0
      - name: Install
        run: yarn
      - name: update apt
        run: apt update
      - name : install java 8
        run : apt-get install openjdk-8-jre-headless -y
      - name: download chromedriver
        run: |
         wget -N https://chromedriver.storage.googleapis.com/90.0.4430.24/chromedriver_linux64.zip -P /github/home/Downloads
         unzip /github/home/Downloads/chromedriver_linux64.zip -d /__w/testDH/testDH/resources/
         ls -al /__w/testDH/testDH/resources
      - name: add 777 permission for Downloads & list path
        run: |
         cd /__w/testDH/testDH
         chmod 777 /__w/testDH/testDH/ && ls -al
      - name: export chromeDriver to $PATH
        run: echo "/__w/testDH/testDH/resources" >> $GITHUB_PATH
      - name: export runtime folder to $PATH
        run: echo "/__w/testDH/testDH" >> $GITHUB_PATH
      - name: echo $path 
        run: echo $PATH
      - name: yarn install on project root dir
        run: |
          cd /__w/testDH/testDH && yarn update
          pwd
          ls -al && cat ./package.json
      #- name: sel install && start
       # run: npx selenium-standalone install && npx selenium-standalone start    
      - name: Test
        run: npx mocha --reporter mochawesome /__w/testDH/testDH/test/Test001.js
