
name: Node.js CI

on:
  push:
    branches: [ koninikita01-patch-1 , master]
  pull_request:
    branches: [ koninikita01-patch-1 ]

jobs:
  e2e-chrome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1.2.0
        with:
          node-version: 14.x
      - run: yarn install
      - run : yarn webdriver-manager update
      - run : pwd && ls -al
      - run:  chmod 777 /home/runner/work/testDH/testDH
#       - name : run start.sh
#         run : npx pm2 start /home/runner/work/testDH/testDH/start.sh
#       - run : yarn webdriver-manager start
#       - run:  yarn jest /test/TC01.test.js
      - run : yarn test:e2e:chrome
#         env:
#           BROWSER: chrome  
#       - run: yarn jest /test/*
#         env:
#           BROWSER: chrome  
