name: Node.js CI

on:
  push:
    branches: [ koninikita01-patch-1 , master]
  pull_request:
    branches: [ koninikita01-patch-1 ]

jobs:
  e2e-chrome:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
#          - browser: "chrome"
         - browser: "firefox"

    steps:
      - name: Checkout
        uses: actions/checkout@v1.2.0
        with:
          node-version: 14.x
      - run: yarn install
      - run: yarn jest /test/*
        env:
         BROWSER: ${{matrix.browser}}  
   
     
          

