
name: Node.js CI

on: 
  push:
    branches: [ test_nk , master]
  pull_request:
    branches: [ test_nk ]

jobs:
  e2e-chrome:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
         - browser: "chrome"
         - browser: "firefox"
    steps:
      - name: Checkout
        uses: actions/checkout@v1.2.0
        with:
          node-version: 14.x
      - run: yarn install
      - run : yarn webdriver-manager update
#       - run : pwd && ls -al
#       - run:  chmod 777 /home/runner/work/testDH/testDH
#       - name : run start.sh
#         run : npx pm2 start /home/runner/work/testDH/testDH/start.sh
#       - run : yarn webdriver-manager start
#       - run:  yarn jest /test/TC01.test.js
      # - run : yarn jest /test/TC01.test.js
      #   env :
      #        BROWSER: ${{matrix.browser}} 
      #        URL: "https://dighybprstaging.z6.web.core.windows.net/"
#       - run: yarn jest /test/*
#         env:
#           BROWSER: ${{matrix.browser}}  
      # - run : yarn test:e2e:chrome --reporters jest-html-reporters --reporters jest-html-reporters     JEST_HTML_REPORTERS_FILE_NAME: TestReport.html
      - run : yarn jest /test/TC.test.js --reporters jest-html-reporters  
        env:
          BROWSER: ${{matrix.browser}} 
          URL: https://stukstswstagingdh.z33.web.core.windows.net/
          JEST_HTML_REPORTERS_FILE_NAME: TestReport+${{matrix.browser}}+.html
      

