
name: Node.js CI

on: 
  push:
    branches: [ test_nk , master]
  pull_request:
    branches: [ test_nk ]

jobs:
  e2e-chrome:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
         - browser: "chrome"
         - browser: "firefox"
    steps:
      - name: Checkout
        uses: actions/checkout@v1.2.0
        with:
          node-version: 14.x
      - run: yarn install
     
      - run : yarn webdriver-manager update
      
      - name: "Get current timestamp"
        id: get-current-timestamp
        run: |
          echo ::set-output name=date::$(date +''%Y-%m-%d-T%H%M%S)
       
      - run : yarn jest /test/TC.test.js --verbose --detectOpenHandles --reporters jest-html-reporters  
        continue-on-error: true
        env:
          BROWSER: ${{matrix.browser}} 
          URL: https://stukstswstagingdh.z33.web.core.windows.net/
          JEST_HTML_REPORTERS_FILE_NAME: TestReport_${{matrix.browser}}_${{steps.get-current-timestamp.date}}.html
          JEST_HTML_REPORTERS_PUBLIC_PATH: ./Reports

      - name : report
        uses: actions/upload-artifact@v2
        with:
          name: Report generated
          path: /home/runner/work/testDH/testDH/Reports/*.html   
        
          
      

