
name: Node.js CI

on:
  push:
    branches: [ koninikita01-patch-1 , master]
  pull_request:
    branches: [ koninikita01-patch-1 ]

jobs:
  e2e-chrome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1.2.0
        with:
          node-version: 14.x
      - run: yarn install
      - name : install java 8
        run : apt-get install openjdk-8-jre-headless -y
      - name : sel install && start
        run : npx selenium-standalone install --silent
      - name : sel start
        run : npx selenium-standalone start
      - run: yarn jest /test/*
        env:
          BROWSER: firefox  
      - run: yarn jest /test/*
        env:
          BROWSER: chrome  
