name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:14.4
      options: --network-alias testHost
    env:
      NODE_ENV: test
      SELENIUM_HUB_HOST: hub
      TEST_HOST: testHost
    services:
      hub:
        image: selenium/hub:3.141.59-gold
      firefox:
        image: selenium/node-firefox:3.141.59-gold
      chrome:
        image: selenium/node-chrome:4.0.0-beta-3-prerelease-20210422
        env:
          HUB_HOST: hub
          HUB_PORT: 4444
    steps:
      - name: Checkout
        uses: actions/checkout@v1.2.0
      - name: Install
        run: yarn
      - name: install chromedriver
        run: apt-get install unzip
      - name : chromedriver
        run: wget -N https://chromedriver.storage.googleapis.com/90.0.4430.24/chromedriver_linux64.zip -P ~/Downloads
      - name: download
        run: unzip ~/Downloads/chromedriver_linux64.zip -d ~/Downloads
      - name: executable
        run: mv -f ~/Downloads/chromedriver /usr/local/share/
      - name: sii
        run: chmod +x /usr/local/share/chromedriver
      - name: path check
        run: echo $PATH
      - name : set path
        run : export PATH=$PATH:/usr/local/share/chromedriver
      - name: homedir
        run: cd $HOME
      - name : env var
        run: vi .bashrc
      - name: edit
        run : i /usr/local/share/chromedriver esc 
      - name : run wq
        run: wq
      - name: path check
        run: echo $PATH
      - name: Test
        run: npx mocha --reporter mochawesome test/*
