name: deploy_ui
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  deploy_ui:
    runs-on: ubuntu-latest
    container:
      image: node:14.4
      options: --network-alias testHost
    env:
      NODE_ENV: test
      SELENIUM_HUB_HOST: hub
      TEST_HOST: testHost
    services:
      hub:
        image: selenium/hub:3.141.59-gold
      firefox:
        image: selenium/node-firefox:3.141.59-gold
      chrome:
        image: selenium/node-chrome:4.0.0-beta-3-prerelease-20210422
        env:
          HUB_HOST: hub
          HUB_PORT: 4444
    steps:
      - name: Checkout
        uses: actions/checkout@v1.2.0
      - name: Install
        run: yarn
      - name: check runtime path
        run: pwd
      - name: list home path
        run: eval echo ~$USER
      - name: install unzip
        run: apt-get install unzip
      - name: download chromedriver
        run: wget -N https://chromedriver.storage.googleapis.com/90.0.4430.24/chromedriver_linux64.zip -P /github/home/Downloads
      - name: unzip to folder
        run: unzip /github/home/Downloads/chromedriver_linux64.zip -d /github/home/Downloads/chromeDriver/
      - name : check unzip folder & list path
        run: cd /github/home/Downloads/chromeDriver/ && ls -al
      - name: add 755 permission & list path
        run: chmod 755 /github/home/Downloads/chromeDriver/ && ls -al
      #- name: executable
       # run: mv -f /github/home/Downloads/chrome/chromeDriver 
      #- name: sii
        #run: chmod 755 /usr/local/share/chromedriver
      - name: echo $PATH
        run: echo $PATH
      - name: export chromeDriver to $PATH
        run: echo "/github/home/Downloads/chromeDriver" >> $GITHUB_PATH
        #run : echo "/usr/local/share/chromedriver" >> $GITHUB_PATH
      - name: echo $path 
        run: echo $PATH
      #- name: run ch 
        #run : cd /usr/local/share/chromedriver
      #- name: ls cmd
        #run: ls -la
      #- name: chrm
        #run : ./chromedriver
      #- name: Test
       # run: npx mocha --reporter mochawesome test/*     
      - shell: bash
        run: |
          echo "Hello! I have been sent from another job. :D" > output.txt
          cat output.txt
      - name: Upload data to next job
        uses: actions/upload-artifact@v2
        with:
          name: data
          path: output.txt
     
  verify_param_from_previous_job:
    needs: deploy_ui
    runs-on: ubuntu-latest
    steps:
      - name: Download data from deploy_ui
        uses: actions/download-artifact@v2
        with:
          name: data
      - shell: bash
        run: |
          value=`cat output.txt`
          echo $value
