name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:14.4
      options: --network-alias testHost
    env:
      NODE_ENV: test
      SELENIUM_HUB_HOST: hub
      TEST_HOST: testHost
    services:
      hub:
        image: selenium/hub:3.141.59-gold
      firefox:
        image: selenium/node-firefox:3.141.59-gold
      chrome:
        image: selenium/node-chrome:4.0.0-beta-3-prerelease-20210422
        env:
          HUB_HOST: hub
          HUB_PORT: 4444
    steps:
      - name: Checkout
        uses: actions/checkout@v1.2.0
      - name: Install
        run: yarn
      - name: install chromedriver
        run: apt-get install unzip
      - name : chromedriver
        run: wget -N https://chromedriver.storage.googleapis.com/90.0.4430.24/chromedriver_linux64.zip -P ~/Downloads
      - name: download
        run: unzip ~/Downloads/chromedriver_linux64.zip -d ~/Downloads
      - name : check
        run: cd /github/home/Downloads
      - name: permission
        run: chmod 755 /github/home/Downloads
      - name: content
        run: ls -la
      - name: executable
        run: mv -f ~/Downloads/chromedriver /usr/local/share/
      - name: sii
        run: chmod 755 /usr/local/share/chromedriver
      - name: path check
        run: echo $PATH
      - name: path check
        run : echo "/usr/local/share/chromedriver" >> $GITHUB_PATH
      - name: path check
        run: echo $PATH
      - name: run ch 
        run : cd /usr/local/share/chromedriver
      - name: ls cmd
        run: ls -la
      - name: chrm
        run : ./chromedriver
      - name: Test
        run: npx mocha --reporter mochawesome test/*
