name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:14.4
      options: --network-alias testHost
    env:
      NODE_ENV: test
      SELENIUM_HUB_HOST: hub
      TEST_HOST: testHost
    services:
      hub:
        image: selenium/hub:3.141.59-gold
      firefox:
        image: selenium/node-firefox:3.141.59-gold
      chrome:
        image: selenium/node-chrome:4.0.0-beta-3-prerelease-20210422
        env:
          HUB_HOST: hub
          HUB_PORT: 4444
    steps:
      - name: Checkout
        uses: actions/checkout@v1.2.0
      - name: Install
        run: yarn
      - name : docker chrome
        run : docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome:4.0.0-beta-3-prerelease-20210422
      - name: Test
        run: npx mocha --reporter mochawesome test/*
